server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dpystart/cloud-config.git
        ####搜索目录
          search-paths:
            - cloud-config
          username: 15236595851
          password: DUANPENGyang521
        ####读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true