server:
  port: 80

spring:
  application:
    name: consumer-feign-order


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7002/eureka/,http://eureka7001.com:7002/eureka/
  instance:
    instance-id: feign-order80
    prefer-ip-address: true

